In [1]:
import numpy as np
n1 = np.array ([10, 20, 30, 40])
n1


array([10, 20, 30, 40])

In [2]:
type(n1)

numpy.ndarray

In [4]:
import numpy as np
n2 = np.array ([[10, 20, 30, 55],[50, 60, 66, 77],[50, 60, 66, 77], [50, 60, 66, 77],[50, 60, 66, 77]])

In [5]:
n3 = np.zeros((4,5))

In [6]:
n3//print

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
n4 = np.full((3,3),9)

In [8]:
n4

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [13]:
n5 = np.arange(1,10)

In [14]:
n5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
n6 = (10,20)

In [16]:
n6


(10, 20)

In [17]:
n5 = np.arange(1,20,3)

In [18]:
n5

array([ 1,  4,  7, 10, 13, 16, 19])

In [25]:
n7 = np.random.randint(10000, 100000, 2)

In [26]:
n7

array([52395, 18651])

In [30]:
n8 = np.random.randint(100, 200, 3)

In [31]:
n8

array([177, 105, 160])

In [32]:
//joining
import numpy as np
n9 = np.array ([[10, 20, 30, 55],[50, 60, 66, 77],[50, 60, 66, 77], [50, 60, 66, 77],[50, 60, 66, 77]])

In [33]:
n9

array([[10, 20, 30, 55],
       [50, 60, 66, 77],
       [50, 60, 66, 77],
       [50, 60, 66, 77],
       [50, 60, 66, 77]])

In [37]:
n9.shape

(4, 5)

In [38]:
n9.shape = (4, 5)


In [39]:
n9

array([[10, 20, 30, 55, 50],
       [60, 66, 77, 50, 60],
       [66, 77, 50, 60, 66],
       [77, 50, 60, 66, 77]])

In [40]:
import numpy as np

In [42]:
a = np.array([10, 20, 30])
b = np.array([30, 40, 50])

In [43]:
np.vstack((a,b)) #joining the numpy as vertical stacking

array([[10, 20, 30],
       [30, 40, 50]])

In [45]:
np.hstack((a, b)) # joining the numpy as horizontal stacking

array([10, 20, 30, 30, 40, 50])

In [47]:
np.column_stack((a, b)) # joining the numpy as column stacking

array([[10, 30],
       [20, 40],
       [30, 50]])

In [48]:
import numpy as np #numpy as intersection and difference